// Solar-farm energy + cost model.
//
// Everything here is a transparent, tunable approximation — the numbers are meant
// to be plausible planning estimates, not a bankable yield study. All physical
// assumptions live in ENERGY so they're easy to find and adjust.
//
// Irradiance bookkeeping: the suitability GeoJSON carries `ghi` as ERA5-Land
// annual surface solar radiation in J/m²/yr (~4.2e9 ≈ 1170 kWh/m²/yr for Bavaria).
// Open-Meteo daily `shortwave_radiation_sum` comes in MJ/m²/day. Both are reduced
// to kWh/m² before the same panel formula is applied.

export const ENERGY = {
  GCR: 0.45, // ground-coverage ratio: panel area per unit of land (rows + gaps)
  MODULE_EFFICIENCY: 0.2, // 20% modules
  PERFORMANCE_RATIO: 0.75, // inverter/thermal/soiling losses
  // Nameplate capacity per m² of *panel* at 1000 W/m² STC, times module efficiency
  // → 0.20 kWp per panel-m². Capacity (kWp) = panel_area_m2 * KWP_PER_PANEL_M2.
  KWP_PER_PANEL_M2: 0.2,
  PRICE_EUR_PER_KWH: 0.08, // wholesale-ish electricity value
  // Maintenance: base O&M plus a grid-distance surcharge (longer interconnection
  // = more line to maintain / higher losses), pro-rated to a monthly figure.
  OM_EUR_PER_KWP_YEAR: 15, // typical utility-scale PV O&M
  GRID_SURCHARGE_EUR_PER_KM_MONTH: 40, // per km of distance to nearest line, monthly
} as const

const J_PER_KWH = 3.6e6
const MJ_PER_KWH = 3.6

export const joulesToKwhPerM2 = (j: number) => j / J_PER_KWH
export const mjToKwhPerM2 = (mj: number) => mj / MJ_PER_KWH

/** Panel area (m²) covered within a land parcel of `areaM2`. */
export function panelArea(areaM2: number): number {
  return areaM2 * ENERGY.GCR
}

/** Installed DC capacity (kWp) for a land parcel of `areaM2`. */
export function capacityKwp(areaM2: number): number {
  return panelArea(areaM2) * ENERGY.KWP_PER_PANEL_M2
}

/**
 * Energy (kWh) generated by `areaM2` of land under `irradianceKwhPerM2` of plane
 * irradiance over some period. Period is whatever the irradiance covers (a day,
 * a month, a year) — pass the summed irradiance for that window.
 */
export function energyKwh(areaM2: number, irradianceKwhPerM2: number): number {
  return panelArea(areaM2) * ENERGY.MODULE_EFFICIENCY * ENERGY.PERFORMANCE_RATIO * irradianceKwhPerM2
}

/** Market value (€) of a quantity of generated energy. */
export function energyValueEur(kwh: number): number {
  return kwh * ENERGY.PRICE_EUR_PER_KWH
}

/**
 * Modeled monthly maintenance cost (€) for a farm: base O&M scaled by capacity,
 * plus a surcharge for distance to the nearest power line (grid proximity).
 */
export function maintenanceEurPerMonth(areaM2: number, distPowerlineM: number | null): number {
  const base = (capacityKwp(areaM2) * ENERGY.OM_EUR_PER_KWP_YEAR) / 12
  const km = distPowerlineM != null ? distPowerlineM / 1000 : 0
  return base + km * ENERGY.GRID_SURCHARGE_EUR_PER_KM_MONTH
}

/** Estimated annual energy (kWh) from the cell's ERA5 annual GHI (J/m²/yr). */
export function annualEnergyKwhFromGhi(areaM2: number, ghiJoules: number | null): number | null {
  if (ghiJoules == null) return null
  return energyKwh(areaM2, joulesToKwhPerM2(ghiJoules))
}

/** Compact human formatter for energy: Wh → kWh → MWh → GWh. */
export function formatKwh(kwh: number): string {
  if (kwh >= 1e6) return `${(kwh / 1e6).toFixed(2)} GWh`
  if (kwh >= 1e3) return `${(kwh / 1e3).toFixed(2)} MWh`
  return `${kwh.toFixed(0)} kWh`
}

/** Compact power formatter: kW → MW. */
export function formatKw(kw: number): string {
  if (kw >= 1e3) return `${(kw / 1e3).toFixed(2)} MW`
  return `${kw.toFixed(0)} kW`
}

/** Euro formatter with thousands separators. */
export function formatEur(eur: number): string {
  const sign = eur < 0 ? "−" : ""
  return `${sign}€${Math.abs(eur).toLocaleString("en-US", { maximumFractionDigits: 0 })}`
}

/** Area formatter: m² up to 1 km², then km². */
export function formatArea(m2: number): string {
  if (m2 >= 1e6) return `${(m2 / 1e6).toFixed(2)} km²`
  return `${m2.toLocaleString("en-US")} m²`
}
